language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
addons:
  sonarcloud:
    organization: dupres@github
    token:
        secure: fcc822d659c1ff67c499bc73b5f430cac1eedae3
script:
  - pytest --cov .
  - sonar-scanner
